### ISSUE TITLE
GIFs import, do not play, washed out color

### ISSUE THREAD

**Issue by tdw46** [neil3d/UnrealAnimatedTexturePlugin#10]
**As you can see, in UE 4.26 the plugin does indeed enable GIF import:**

![image](https://user-images.githubusercontent.com/10996763/114127804-f66aaf00-98c8-11eb-9f44-91cfe9ca0c1c.png)
![image](https://user-images.githubusercontent.com/10996763/114127669-ac81c900-98c8-11eb-8c72-6d01efc834e1.png)

However, after importing, GIFs don't play, they appear washed out, and they aren't recognized as 2D texture objects usable with things like UI elements.

Any idea what the issue here is?

Here's the original GIF I'm working with:
![Endeavor_HealthIcon](https://user-images.githubusercontent.com/10996763/114127990-5c573680-98c9-11eb-83ee-835552020fc7.gif)

**Comment by tdw46** [comment]
Here's a look at the original GIF file I am working with.

![Endeavor_HealthIcon](https://user-images.githubusercontent.com/10996763/114127908-35006980-98c9-11eb-93d4-c51999ee9220.gif)

**Comment by neil3d** [comment]
Fixed by set bIgnoreGammaConversions = true;
Please checkout 0.4.6: [https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/tag/v0.4.6](https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/tag/v0.4.6)
