### ISSUE TITLE
Update for UE5

### ISSUE THREAD

**Issue by kalasaceo** [neil3d/UnrealAnimatedTexturePlugin#11]
kindly update your awesome ue4animated texture plugin for ue5

**Comment by GMatrixGames** [comment]
+1, would be a nice to have!

**Comment by indu111** [comment]
+1 !!! :)

**Comment by neil3d** [comment]
I'm working on UE5 version in a separate repo:  [https://github.com/neil3d/UAnimatedTexture5](https://github.com/neil3d/UAnimatedTexture5). It works now, and supports GIF and WebP(true-color animation)
