### ISSUE TITLE
褪色的问题

### ISSUE THREAD

**Issue by robot518** [neil3d/UnrealAnimatedTexturePlugin#13]
将gif图放到image上依然还是褪色的，你这几天修复的那个褪色问题只有在编辑器上显示的时候不褪色

**Comment by neil3d** [comment]
你可以试一下 dev 分支的版本吗？
如果还不行，是否可以提供你的 gif 文件，和你的具体情况的截图？

**Comment by robot518** [comment]
> 

您在dev分支的最新提交，修复了褪色的问题，谢谢

**Comment by neil3d** [comment]
[0.4.7版本已经更新](https://github.com/neil3d/UAnimatedTexture4/releases/tag/0.4.7)
