### ISSUE TITLE
Can't get this to open in 4.21. Put in plugins and get errors.

### ISSUE THREAD

**Issue by Kl3tus** [neil3d/UnrealAnimatedTexturePlugin#5]
So after putting in plugins and launching my project, I get ' The following modules are missing or built with a different engine version: animatedtexture animatedtextureeditor ' . 

Rebuild fails, tried 4.0 all the way down to 1.0, 1.0 had a different error message saying it was built for 4.22 but it still fails. 

Any advice?

**Comment by neil3d** [comment]
The last version not tested with 4.21. You can check out the old release: [https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/download/v0.4.2/AnimatedTexture_042_421.zip](https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/download/v0.4.2/AnimatedTexture_042_421.zip) 
or download from the marketplace: [https://www.unrealengine.com/marketplace/en-US/product/animated-texture-with-gif-importer?lang=en-US](https://www.unrealengine.com/marketplace/en-US/product/animated-texture-with-gif-importer?lang=en-US)
