### ISSUE TITLE
Crashes UE 4.25.3 upon importing gifs because of DirectX 12 setting

### ISSUE THREAD

**Issue by indu111** [neil3d/UnrealAnimatedTexturePlugin#6]
Hello! First off, kudos to the author for making this utility free and it genuinely is very versatile. Thank you! 
I posted this on marketplace as well, thought I would post it here so I could bring this to your attention. 

If you tried to create a blank template (I chose empty Gaming template) with the bare minimum in it and then after activating the plugin, tried to import a GIF (in UE 4.25.3 atleast for me), it would crash immediately.

So I downloaded the demo scene you have prepared here on Github and opened my scene side by side and literally sat for hours and compared every project setting to see what was different. And I found out that if you took your working demo scene, converted and opened in 4.25 (and it still works at this point and imports gifs fine) but simply changed the following setting, you can make your scene crash too upon import.

And the setting is Project Settings > Platforms > Windows > Default RHI : Direct X 12.
By default in previous versions of UE, this setting might have been set to Default but newer versions it is set to Direct X 12 which makes it crash.

If you set it back to Default then you can successfully use this tool. HOWEVER, I would like to request the author to kindly fix this bug so we all can use DirectX 12 while also using this awesome utility.

Cheers

Indy

**Comment by neil3d** [comment]
Bug fixed. It works with DirectX12 RHI on 4.25.3. Please check out this release: [https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/tag/v0.4.4](https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/tag/v0.4.4)

**Comment by indu111** [comment]
Hey! Thank you so much for quick fixing this! I am a bit of noob when it comes to grabbing plugins from here. So I just download AnimatedTexturePlugin.zip that you have linked above and then copy all its contents to C:\Program Files\Epic Games\UE_4.25\Engine\Plugins\Marketplace\AnimatedTexture
Correct?

**Comment by indu111** [comment]
So I copied all the contents of the AnimatedTexturePlugin.zip you have linked above, extracted it and copied all its contents to C:\Program Files\Epic Games\UE_4.25\Engine\Plugins\Marketplace\AnimatedTexture
Then I downloaded your demo project from here: https://github.com/neil3d/UnrealCookbook/tree/master/AnimatedGIFDemo
Launched it from Epic Launcher UE where it asks to rebuild the project so I clicked Yes and the project launches with some error messages. I go to plugins and find Animated Texture Plugin and turn it on, it shows v0.4.4 as the correct version number. I also switched the Default RHI to Default. 
Restart the editor and upon opening, the gifs load perfectly without errors. However, just like before, once I flip to DirectX 12, UE4 crashes everytime upon opening the project.

So I am not sure, if I made any mistake copying the plugin correctly or is the bug still existing??

I can provide a video recording of this process if you would like or copy paste the crash error log. Please let me know, I can't wait to get it to work with DirectX 12 ! 
:) Thank you so much for your hard work !

Indy

**Comment by indu111** [comment]
Hello @neil3d can we get an update to the Default RHI bug? The 0.4.4 doesn't seem to fix, my project really needs gifs and DirectX12, can I please get in touch with you?

**Comment by neil3d** [comment]
> Hello @neil3d can we get an update to the Default RHI bug? The 0.4.4 doesn't seem to fix, my project really needs gifs and DirectX12, can I please get in touch with you?

I have just submitted a file update to Unreal Engine Marketplace, a new version will be shown soon.
If you want to update manually, please checkout : [https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/tag/v0.4.5](https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/tag/v0.4.5)

**Comment by indu111** [comment]
YAYYYYYYYY!!! It finally works! THANK YOU SO MUCH!

Here's what I did for anyone trying and going through similar issue. Download the zip file here (I got 425): 
https://github.com/neil3d/UnrealAnimatedTexturePlugin/releases/tag/v0.4.5

Extract the zip and go to your project. If it doesn't have a folder already, make a folder called Plugins in the same directory as to where you uproject file is. Paste the entire AnimatedTexturePlugin folder in there. The moment you launch your project now, it will ask to rebuild the plugin, go ahead and let it rebuild. Once open, go to your Plugins windows in UE and under Built in section, make sure Animated Texture Plugin is checked on.

Now with the latest patch, even with Default RHI set to DirectX12, you can easily import any gif directly into UE content browser and get started!

THANK YOU SO MUCH ONCE AGAIN @neil3d for quickly addressing the issue. I will change my rating and review on UE marketplace now that it works flawlessly for me!
You can mark this issue as solved/closed.

Cheers

Indy
