### ISSUE TITLE
GIF导入后 图片变亮了

### ISSUE THREAD

**Issue by shmiluyu** [neil3d/UnrealAnimatedTexturePlugin#7]
![image](https://user-images.githubusercontent.com/2082615/96950669-694fbb80-151d-11eb-8b8d-3d69a2d9e341.png)

调了一下亮度,对比度,不起作用好像.

环境:
1. win10 
1. ue4.25.1
1. 直接clone的master
1. vs2019

测试GIF
![image](https://i.pinimg.com/originals/c9/b1/8d/c9b18d83e5e46052338cd12327b92080.gif)

**Comment by neil3d** [comment]
具体原因很难想象出来，你可以提供这个 GIF 文件吗？我查查看

**Comment by shmiluyu** [comment]
谢谢回复, 是很奇怪呀, 最后我直接下载市场的,不自己编译了.好像就正常了.........
