### ISSUE TITLE
When will an update come for 4.26?

### ISSUE THREAD

**Issue by nanogram** [neil3d/UnrealAnimatedTexturePlugin#8]

**Comment by helghast** [comment]
+1. same question here.

**Comment by orwel1984** [comment]
+1 same. 
Started a project using this plugin and now the whole thing is stucked.

**Comment by neil3d** [comment]
I have just merged a PR for 4.26, but not tested yet.

**Comment by nanogram** [comment]
tested it. seems to work fine as in previous versions.

**Comment by neil3d** [comment]
EPIC Marketplace -file update complete

**Comment by orwel1984** [comment]
The Epic Marketplace is unable to install it into 4.26 for many days now. 
Can you check if it is working ?

**Comment by neil3d** [comment]
> The Epic Marketplace is unable to install it into 4.26 for many days now.
> Can you check if it is working ?

I am trying to upload it again.

**Comment by neil3d** [comment]
![image](https://user-images.githubusercontent.com/4220016/104413215-e765b080-55a8-11eb-9d9e-a58b3f21e23a.png)

Marketplace version 4.26 just works now.
